src/pages/usuarios/index.tsx

Reverts fga-eps-mds/2023-1-schedula-front#2

Revert "Fix: Callback user parameter"

---

src/components/side-bar/sidebar-item/index.tsx
src/components/side-bar/sidebar-item/sidebar-item.spec.tsx
src/constants/routes.ts

Adicionando regra de negócio de permissões de cada usuário

Defining each user's permissions

---

src/features/tutorials/components/delete-tutorial-modal/index.tsx
src/features/tutorials/components/tutorial-delete-form/index.tsx
src/features/tutorials/components/tutorial-form/indext.tsx
src/features/tutorials/components/tutorial-modal/index.tsx
src/pages/tutorial-temp/index.tsx

Adicionando tela de popUp ao criar ou deletar um tutorial.
Este PR está relacionado a história de usuário #28
Criar um plano de testes
- Melhorar a tela de popUp; 
- adicionar os cards para os tutoriais;

#28 pop up

---

src/pages/gerenciar-tutorial/index.tsx

Adicionando o selectbox na tela de gerenciamento de tutorial para filtrar categorias
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/28

feat: #28 - Adding Select Box on tutorial manage screen

---

src/features/categories-tutorial/components/category-tutorial-form/category-tutorial-form.spec.tsx
src/features/categories-tutorial/components/category-tutorial-item/category-tutorial-item.spec.tsx

Só ajustando alguns prints que não estavam condizentes com as de categorias de tutorial no arquivos de teste.
Relacionado a [Issue #25](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/25)
Verificar se os testes vão passar mesmo no CI.

fix: #25 fixing some prints in test files

---

sonar-project.properties
src/features/cities/api/get-all-cities.ts
src/features/issues/components/issue-form/create-issue-form.tsx
src/features/issues/components/issue-item/index.tsx
src/features/workstations/components/workstation-form/index.tsx
src/pages/cidades/cities.spec.tsx
src/pages/cidades/index.tsx

Resolvendo bug de deleção e criação de cidades.
Resolve [Issue #59](https://github.com/fga-eps-mds/2023-1-schedula-doc/issues/59)
Testar as funcionalidades de deleção e edição de cidades

#59 fix bug localization

---

src/components/permission/index.tsx
src/components/side-bar/sidebar-item/index.tsx
src/components/side-bar/sidebar-item/sidebar-item.spec.tsx
src/constants/routes.ts
src/features/users/api/types.ts
src/features/users/components/user-form/index.tsx
src/features/users/components/user-item/user-item.spec.tsx
src/features/users/components/user-modal/index.tsx
src/pages/chamados/index.tsx
src/types/usuarios.d.ts

Este PR serve tanto para adicionar o CPF no cadastro do usuário quanto para corrigir algumas regras de usuários que foram validadas com o Guilherme Pupak
Resolve [Issue #67](https://github.com/fga-eps-mds/2023-1-schedula-doc/issues/67)
Validar se é possível inserir CPF correto, incorreto e ou inválido, além de editar.

#67 Add CPF to users

---

src/pages/tutoriais/index.tsx

Este PR serve para adicionar a funcionalidade solicitada pelos clientes de listar tutoriais ordenados de maneira crescente alfabética pelo seu título.
Resolve tarefa da issue [issue #27](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/27)
Verificar se a lista de tutoriais disponíveis é gerada, e se está ordenada pelo título do tutorial.
Ao clicar em "Download", o arquivo .pdf do tutorial deve ser aberto em outra guia do navegador.

feat: sort tutorials by name

---

src/features/workstations/components/workstation-form/index.tsx

Corrigindo placeholder do gateway no posto de trabalho
Reolve [#99](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/99)

#99 Fix gateway placeholder

---

src/features/tutorials/components/tutorial-form/index.tsx
src/features/tutorials/components/tutorial-modal/index.tsx

Resgatar os valores dos tutoriais para o campo de edição. Além disso, fazer com que o campo de arquivo receba somente arquivos .pdf.
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/80
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/100

#80 edicao tutorial

---

src/pages/chamados/chamados.spec.tsx
src/pages/chamados/index.tsx

Ordenando os atendimentos corretamente na tela de atendimentos.
Resolve [Issue #109](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/109)
A tela de atendimentos agora mostra os atendimentos ordenados do mais recente para o mais antigo.
Criar atendimentos e verificar que independentemente da forma que sejam criados, sejam sempre mostrados do mais recente para o mais antigo.

#109 ordenacao atendimentos

---

src/pages/agendamentos/index.tsx
src/pages/chamados/chamados.spec.tsx
src/pages/chamados/index.tsx

Removendo agendamentos resolvidos da tela de agendamentos.
Resolve [Issue #111](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/111)
Agora agendamentos marcados como resolvidos não aparecem mais na tela de agendamentos.
Mudar o status de um agendamento para "Resolvido", para verificar que o mesmo some da tela de agendamentos. Agendamentos de todos os outros tipos de status continuarão aparecendo na tela.

#111 agendamentos resolvidos

---

src/features/tutorials/components/tutorial-modal/index.tsx
src/features/workstations/components/workstation-form/index.tsx
src/features/workstations/components/workstation-modal/workstation-modal.tsx

Adicionando tratamento de erro quando o campo cidade não é preenchido.
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/102

fix: #102 adding city_id error treatment

---

src/features/issues/components/issue-form/create-issue-form-open.tsx

Na tela de Registrar Agendamento para o usuário externo, estar mostrando as categorias e tipos de problemas que o admin marcou como visível para usuários externos.
Resolve [#119](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/119)

#119 fixing category and type filter problem

---

src/features/workstations/components/workstation-form/workstation-form.spec.tsx

Adicionando testes para o workstation-form.
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/118

#118 Adding tests for workstation-form

---

src/features/tutorials/components/tutorial-form/index.tsx
src/pages/gerenciar-tutorial/index.tsx
src/pages/tutoriais/index.tsx

Permite a edição de tutorial com ou sem arquivo novo
[#Issue 114](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/114)
Depende do [PR#6](https://github.com/fga-eps-mds/2023-1-schedula-gerenciador-de-tutoriais/pull/6) para execução
- Testar se a criação de tutorias esta correta COM e SEM arquivo, validando os erros
- Testar se a edição esta correta COM e SEM arquivo

#114 bug edicao tutorial

---

src/features/categories-tutorial/api/get-all-categories-tutorial.ts
src/features/tutorials/components/tutorial-form/index.tsx
src/pages/categorias_de_tutorial/categorias_de_tutorial.spec.tsx
src/pages/categorias_de_tutorial/index.tsx

Resolvendo bug de deleção e criação de categorias.
Resolve [Issue #78](https://github.com/fga-eps-mds/2023-1-schedula-doc/issues/78)
Testar as funcionalidades de deleção e edição de categorias

#78 fixing categorie editing and deletion bug

---

src/pages/agendamentos_abertos/agendamentos_abertos.spec.tsx
src/pages/agendamentos_abertos/index.tsx

Adicionando os agendamentos criados por usuários externos na página de agendamentos abertos.
resolve [Issue #128](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/128)

feat: adding Schedule-Open to Agendamentos Abertos

---

src/features/schedules/components/schedule-table-item/index.tsx
src/features/schedules/components/schedule-table-item/schedule-table-item.spec.tsx
src/pages/exportacao_agendamentos/exportacao-agendamentos.spec.tsx
src/pages/exportacao_agendamentos/index.tsx

Adicionando duas novas colunas para o arquivo de exportação de agendamentos. Sendo eles posto de trabalho e atendente.
[#124_AdicionarDadosExportacao](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/124)

feat: Adding new table collumns for export schedule

---

src/pages/chamados/chamados.spec.tsx
src/pages/chamados/index.tsx

#44 filtrar atendimentos

---

src/features/schedules/components/schedule-form/schedule-form.spec.tsx
src/features/users/components/user-form/user-form.spec.tsx

Adicionando testes para em schedule-form e user-form
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/132

feat: Adding tests for schedule-form and user-form

---

src/features/schedules/components/schedule-table-item/index.tsx
src/features/schedules/components/schedule-table-item/schedule-table-item.spec.tsx
src/pages/exportacao_agendamentos/index.tsx

Adicionando colunas no documento de exportação de agendamentos. Sendo elas, telefone do posto de trabalho e nome do posto de trabalho.
](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/134)

Fix: #134 Adding new columns for export schedule

---

src/pages/cidades/index.tsx

Removendo bug identificado pelo SonarCloud
Resolve [Issue #142](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/142)

#142 removing bug

---

src/features/issues/components/issue-form/create-issue-form.spec.tsx
src/features/schedules/components/schedule-edit-form/schedule-edit-form.spec.tsx
src/features/schedules/components/schedule-open-item/schedule-open-item.spec.tsx

Adicionando testes para schedule-edit-form, schedule-open-item e create-issue-form
https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/140

feat: Adding tests for schedule-edit-form, schedule-open-item and create-issue-form.

---

src/pages/chamados/chamados.spec.tsx

Aumento na cobertura de teste do arquivo de chamados, na pasta pages.
[#143](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/143)

test: increase issues page test coverage

---

metrics/sonar-metrics.py
src/features/api-status/api/get-alert-api-status.ts
src/features/api-status/api/get-alert-release-version.ts
src/features/api-status/constants/cache.ts
src/features/api-status/hooks/use-api-status.ts
src/features/api-status/hooks/use-release-data.ts
src/features/issues/components/issue-item/index.tsx
src/pages/exportacao_agendamentos/index.tsx

Adicionando checagem de disponibilidade do microsserviço de alertas
Resolve [Issue #136](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/136)
Agora aparece um aviso em tela caso o microsserviço de alerta esteja indisponível.
(Foi realizado também pequenas modificações em telas que não tratavam objetos como array corretamente)

#136 api status alertas

---

src/components/action-buttons/approve-button-homologation/index.tsx
src/features/homologations/components/issue-open-edit-form/index.tsx
src/features/homologations/components/issue-open-item/index.tsx

Retirando o botão de alerta em homologação (edição e aprovação) e arrumando a passagem de parâmetro da data de agendamento quando a pessoa só coloca na hora de aprovar.
[Issue #131](https://github.com/fga-eps-mds/2023-1-Schedula-Doc/issues/131)
1) Ver se o botão de alertas está aparecendo.
2) Ver se a data de agendamento está passando certo pra página de agendamentos.

fix: #131 removing alert button in homologation and fixing a dateTime problem
